// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: message.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TextServiceClient is the client API for TextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextServiceClient interface {
	TextFunc(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error)
}

type textServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextServiceClient(cc grpc.ClientConnInterface) TextServiceClient {
	return &textServiceClient{cc}
}

func (c *textServiceClient) TextFunc(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error) {
	out := new(TextResponse)
	err := c.cc.Invoke(ctx, "/TextService/TextFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextServiceServer is the server API for TextService service.
// All implementations must embed UnimplementedTextServiceServer
// for forward compatibility
type TextServiceServer interface {
	TextFunc(context.Context, *TextRequest) (*TextResponse, error)
	mustEmbedUnimplementedTextServiceServer()
}

// UnimplementedTextServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTextServiceServer struct {
}

func (UnimplementedTextServiceServer) TextFunc(context.Context, *TextRequest) (*TextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TextFunc not implemented")
}
func (UnimplementedTextServiceServer) mustEmbedUnimplementedTextServiceServer() {}

// UnsafeTextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextServiceServer will
// result in compilation errors.
type UnsafeTextServiceServer interface {
	mustEmbedUnimplementedTextServiceServer()
}

func RegisterTextServiceServer(s grpc.ServiceRegistrar, srv TextServiceServer) {
	s.RegisterService(&TextService_ServiceDesc, srv)
}

func _TextService_TextFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServiceServer).TextFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TextService/TextFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServiceServer).TextFunc(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextService_ServiceDesc is the grpc.ServiceDesc for TextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TextService",
	HandlerType: (*TextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TextFunc",
			Handler:    _TextService_TextFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

// BytesServiceClient is the client API for BytesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BytesServiceClient interface {
	BytesFunc(ctx context.Context, in *BytesRequest, opts ...grpc.CallOption) (*BytesResponse, error)
}

type bytesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBytesServiceClient(cc grpc.ClientConnInterface) BytesServiceClient {
	return &bytesServiceClient{cc}
}

func (c *bytesServiceClient) BytesFunc(ctx context.Context, in *BytesRequest, opts ...grpc.CallOption) (*BytesResponse, error) {
	out := new(BytesResponse)
	err := c.cc.Invoke(ctx, "/BytesService/BytesFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BytesServiceServer is the server API for BytesService service.
// All implementations must embed UnimplementedBytesServiceServer
// for forward compatibility
type BytesServiceServer interface {
	BytesFunc(context.Context, *BytesRequest) (*BytesResponse, error)
	mustEmbedUnimplementedBytesServiceServer()
}

// UnimplementedBytesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBytesServiceServer struct {
}

func (UnimplementedBytesServiceServer) BytesFunc(context.Context, *BytesRequest) (*BytesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BytesFunc not implemented")
}
func (UnimplementedBytesServiceServer) mustEmbedUnimplementedBytesServiceServer() {}

// UnsafeBytesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BytesServiceServer will
// result in compilation errors.
type UnsafeBytesServiceServer interface {
	mustEmbedUnimplementedBytesServiceServer()
}

func RegisterBytesServiceServer(s grpc.ServiceRegistrar, srv BytesServiceServer) {
	s.RegisterService(&BytesService_ServiceDesc, srv)
}

func _BytesService_BytesFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BytesServiceServer).BytesFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BytesService/BytesFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BytesServiceServer).BytesFunc(ctx, req.(*BytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BytesService_ServiceDesc is the grpc.ServiceDesc for BytesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BytesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BytesService",
	HandlerType: (*BytesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BytesFunc",
			Handler:    _BytesService_BytesFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

// BigDataServiceClient is the client API for BigDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BigDataServiceClient interface {
	BigDataFunc(ctx context.Context, in *BigDataRequest, opts ...grpc.CallOption) (*BigDataResponse, error)
}

type bigDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBigDataServiceClient(cc grpc.ClientConnInterface) BigDataServiceClient {
	return &bigDataServiceClient{cc}
}

func (c *bigDataServiceClient) BigDataFunc(ctx context.Context, in *BigDataRequest, opts ...grpc.CallOption) (*BigDataResponse, error) {
	out := new(BigDataResponse)
	err := c.cc.Invoke(ctx, "/BigDataService/BigDataFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BigDataServiceServer is the server API for BigDataService service.
// All implementations must embed UnimplementedBigDataServiceServer
// for forward compatibility
type BigDataServiceServer interface {
	BigDataFunc(context.Context, *BigDataRequest) (*BigDataResponse, error)
	mustEmbedUnimplementedBigDataServiceServer()
}

// UnimplementedBigDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBigDataServiceServer struct {
}

func (UnimplementedBigDataServiceServer) BigDataFunc(context.Context, *BigDataRequest) (*BigDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BigDataFunc not implemented")
}
func (UnimplementedBigDataServiceServer) mustEmbedUnimplementedBigDataServiceServer() {}

// UnsafeBigDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BigDataServiceServer will
// result in compilation errors.
type UnsafeBigDataServiceServer interface {
	mustEmbedUnimplementedBigDataServiceServer()
}

func RegisterBigDataServiceServer(s grpc.ServiceRegistrar, srv BigDataServiceServer) {
	s.RegisterService(&BigDataService_ServiceDesc, srv)
}

func _BigDataService_BigDataFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BigDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigDataServiceServer).BigDataFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BigDataService/BigDataFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigDataServiceServer).BigDataFunc(ctx, req.(*BigDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BigDataService_ServiceDesc is the grpc.ServiceDesc for BigDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BigDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BigDataService",
	HandlerType: (*BigDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BigDataFunc",
			Handler:    _BigDataService_BigDataFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
