// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: message.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TextserviceClient is the client API for Textservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextserviceClient interface {
	Textfunc(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error)
}

type textserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextserviceClient(cc grpc.ClientConnInterface) TextserviceClient {
	return &textserviceClient{cc}
}

func (c *textserviceClient) Textfunc(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error) {
	out := new(TextResponse)
	err := c.cc.Invoke(ctx, "/Textservice/textfunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextserviceServer is the server API for Textservice service.
// All implementations must embed UnimplementedTextserviceServer
// for forward compatibility
type TextserviceServer interface {
	Textfunc(context.Context, *TextRequest) (*TextResponse, error)
	mustEmbedUnimplementedTextserviceServer()
}

// UnimplementedTextserviceServer must be embedded to have forward compatible implementations.
type UnimplementedTextserviceServer struct {
}

func (UnimplementedTextserviceServer) Textfunc(context.Context, *TextRequest) (*TextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Textfunc not implemented")
}
func (UnimplementedTextserviceServer) mustEmbedUnimplementedTextserviceServer() {}

// UnsafeTextserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextserviceServer will
// result in compilation errors.
type UnsafeTextserviceServer interface {
	mustEmbedUnimplementedTextserviceServer()
}

func RegisterTextserviceServer(s grpc.ServiceRegistrar, srv TextserviceServer) {
	s.RegisterService(&Textservice_ServiceDesc, srv)
}

func _Textservice_Textfunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextserviceServer).Textfunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Textservice/textfunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextserviceServer).Textfunc(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Textservice_ServiceDesc is the grpc.ServiceDesc for Textservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Textservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Textservice",
	HandlerType: (*TextserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "textfunc",
			Handler:    _Textservice_Textfunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

// TexthandlerClient is the client API for Texthandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TexthandlerClient interface {
	SayText(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type texthandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewTexthandlerClient(cc grpc.ClientConnInterface) TexthandlerClient {
	return &texthandlerClient{cc}
}

func (c *texthandlerClient) SayText(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Texthandler/SayText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TexthandlerServer is the server API for Texthandler service.
// All implementations must embed UnimplementedTexthandlerServer
// for forward compatibility
type TexthandlerServer interface {
	SayText(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedTexthandlerServer()
}

// UnimplementedTexthandlerServer must be embedded to have forward compatible implementations.
type UnimplementedTexthandlerServer struct {
}

func (UnimplementedTexthandlerServer) SayText(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayText not implemented")
}
func (UnimplementedTexthandlerServer) mustEmbedUnimplementedTexthandlerServer() {}

// UnsafeTexthandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TexthandlerServer will
// result in compilation errors.
type UnsafeTexthandlerServer interface {
	mustEmbedUnimplementedTexthandlerServer()
}

func RegisterTexthandlerServer(s grpc.ServiceRegistrar, srv TexthandlerServer) {
	s.RegisterService(&Texthandler_ServiceDesc, srv)
}

func _Texthandler_SayText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TexthandlerServer).SayText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Texthandler/SayText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TexthandlerServer).SayText(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Texthandler_ServiceDesc is the grpc.ServiceDesc for Texthandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Texthandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Texthandler",
	HandlerType: (*TexthandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayText",
			Handler:    _Texthandler_SayText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
